"""Unit tests for validation utilities."""

import pytest
import uuid
from fastapi import HTTPException

from backend.utils.validation import (
    is_valid_uuid_v4,
    validate_session_id,
    generate_session_id,
)


class TestIsValidUUIDv4:
    """Tests for UUID v4 format validation."""

    def test_valid_uuid_v4_lowercase(self) -> None:
        """Valid lowercase UUID v4 should return True."""
        valid_uuid = "550e8400-e29b-41d4-a716-446655440000"
        assert is_valid_uuid_v4(valid_uuid) is True

    def test_valid_uuid_v4_uppercase(self) -> None:
        """Valid uppercase UUID v4 should return True."""
        valid_uuid = "550E8400-E29B-41D4-A716-446655440000"
        assert is_valid_uuid_v4(valid_uuid) is True

    def test_valid_uuid_v4_mixed_case(self) -> None:
        """Valid mixed-case UUID v4 should return True."""
        valid_uuid = "550e8400-E29B-41d4-A716-446655440000"
        assert is_valid_uuid_v4(valid_uuid) is True

    def test_generated_uuid_v4_is_valid(self) -> None:
        """UUID generated by Python's uuid.uuid4() should be valid."""
        generated = str(uuid.uuid4())
        assert is_valid_uuid_v4(generated) is True

    def test_invalid_uuid_v1_format(self) -> None:
        """UUID v1 format should be rejected (first digit of 3rd group not '4')."""
        uuid_v1 = "550e8400-e29b-11d4-a716-446655440000"  # '1' instead of '4'
        assert is_valid_uuid_v4(uuid_v1) is False

    def test_invalid_short_string(self) -> None:
        """Short string should be rejected."""
        assert is_valid_uuid_v4("ses_12345678") is False

    def test_invalid_no_hyphens(self) -> None:
        """UUID without hyphens should be rejected."""
        assert is_valid_uuid_v4("550e8400e29b41d4a716446655440000") is False

    def test_invalid_empty_string(self) -> None:
        """Empty string should be rejected."""
        assert is_valid_uuid_v4("") is False

    def test_invalid_none(self) -> None:
        """None should be rejected."""
        assert is_valid_uuid_v4(None) is False  # type: ignore

    def test_invalid_non_string(self) -> None:
        """Non-string should be rejected."""
        assert is_valid_uuid_v4(12345) is False  # type: ignore

    def test_invalid_malformed_uuid(self) -> None:
        """Malformed UUID should be rejected."""
        assert is_valid_uuid_v4("not-a-uuid-at-all") is False


class TestValidateSessionID:
    """Tests for session_id validation with HTTPException."""

    def test_valid_session_id_returns_id(self) -> None:
        """Valid session_id should be returned unchanged."""
        valid_id = str(uuid.uuid4())
        result = validate_session_id(valid_id)
        assert result == valid_id

    def test_invalid_session_id_raises_404(self) -> None:
        """Invalid session_id should raise HTTPException with 404."""
        with pytest.raises(HTTPException) as exc_info:
            validate_session_id("ses_12345678")

        assert exc_info.value.status_code == 404
        assert exc_info.value.detail["error"] == "SESSION_NOT_FOUND"

    def test_empty_session_id_raises_404(self) -> None:
        """Empty session_id should raise HTTPException with 404."""
        with pytest.raises(HTTPException) as exc_info:
            validate_session_id("")

        assert exc_info.value.status_code == 404

    def test_malformed_session_id_raises_404(self) -> None:
        """Malformed session_id should raise HTTPException with 404."""
        with pytest.raises(HTTPException) as exc_info:
            validate_session_id("not-a-valid-uuid")

        assert exc_info.value.status_code == 404

    def test_uuid_v1_format_raises_404(self) -> None:
        """UUID v1 format should raise HTTPException with 404."""
        uuid_v1 = "550e8400-e29b-11d4-a716-446655440000"
        with pytest.raises(HTTPException) as exc_info:
            validate_session_id(uuid_v1)

        assert exc_info.value.status_code == 404


class TestGenerateSessionID:
    """Tests for session_id generation."""

    def test_generates_valid_uuid_v4(self) -> None:
        """Generated session_id should be valid UUID v4."""
        session_id = generate_session_id()
        assert is_valid_uuid_v4(session_id) is True

    def test_generates_unique_ids(self) -> None:
        """Consecutive calls should generate different IDs."""
        id1 = generate_session_id()
        id2 = generate_session_id()
        assert id1 != id2

    def test_generated_id_passes_validation(self) -> None:
        """Generated ID should pass validate_session_id."""
        session_id = generate_session_id()
        result = validate_session_id(session_id)
        assert result == session_id
