"""Initial migration

Revision ID: b318c97515a6
Revises:
Create Date: 2026-01-08 10:46:24.586669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b318c97515a6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('topic', sa.Enum('WHOLE_NUMBERS', 'FRACTIONS', 'DECIMALS', 'PERCENTS', 'RATIOS', 'INTEGERS', 'ORDER_OF_OPERATIONS', 'EXPRESSIONS', 'ONE_STEP_EQUATIONS', 'TWO_STEP_EQUATIONS', 'LINEAR_EQUATIONS', 'SYSTEMS_OF_EQUATIONS', 'QUADRATIC_EQUATIONS', 'INEQUALITIES', 'AREA_PERIMETER', 'VOLUME_SURFACE_AREA', 'ANGLES', 'TRIANGLES', 'COORDINATE_GEOMETRY', 'MEAN_MEDIAN_MODE', 'PROBABILITY', 'UNKNOWN', name='mathtopic'), nullable=True))
    op.add_column('problems', sa.Column('grade_level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problems', 'grade_level')
    op.drop_column('problems', 'topic')
    # ### end Alembic commands ###
